package com.baohao.departmentwebsitefrontend.model;

import java.util.Date;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.arti_id
     *
     * @mbg.generated
     */
    private Integer artiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.arti_name
     *
     * @mbg.generated
     */
    private String artiName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.arti_author
     *
     * @mbg.generated
     */
    private String artiAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.arti_id
     *
     * @return the value of article.arti_id
     *
     * @mbg.generated
     */
    public Integer getArtiId() {
        return artiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.arti_id
     *
     * @param artiId the value for article.arti_id
     *
     * @mbg.generated
     */
    public void setArtiId(Integer artiId) {
        this.artiId = artiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.arti_name
     *
     * @return the value of article.arti_name
     *
     * @mbg.generated
     */
    public String getArtiName() {
        return artiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.arti_name
     *
     * @param artiName the value for article.arti_name
     *
     * @mbg.generated
     */
    public void setArtiName(String artiName) {
        this.artiName = artiName == null ? null : artiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.arti_author
     *
     * @return the value of article.arti_author
     *
     * @mbg.generated
     */
    public String getArtiAuthor() {
        return artiAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.arti_author
     *
     * @param artiAuthor the value for article.arti_author
     *
     * @mbg.generated
     */
    public void setArtiAuthor(String artiAuthor) {
        this.artiAuthor = artiAuthor == null ? null : artiAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.create_time
     *
     * @return the value of article.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.create_time
     *
     * @param createTime the value for article.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.update_time
     *
     * @return the value of article.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.update_time
     *
     * @param updateTime the value for article.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}