package com.baohao.departmentwebsitefrontend.model;

public class FnInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fn_info.fn_id
     *
     * @mbg.generated
     */
    private Integer fnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fn_info.fn_name
     *
     * @mbg.generated
     */
    private String fnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fn_info.fn_number
     *
     * @mbg.generated
     */
    private Integer fnNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fn_info.fn_id
     *
     * @return the value of fn_info.fn_id
     *
     * @mbg.generated
     */
    public Integer getFnId() {
        return fnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fn_info.fn_id
     *
     * @param fnId the value for fn_info.fn_id
     *
     * @mbg.generated
     */
    public void setFnId(Integer fnId) {
        this.fnId = fnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fn_info.fn_name
     *
     * @return the value of fn_info.fn_name
     *
     * @mbg.generated
     */
    public String getFnName() {
        return fnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fn_info.fn_name
     *
     * @param fnName the value for fn_info.fn_name
     *
     * @mbg.generated
     */
    public void setFnName(String fnName) {
        this.fnName = fnName == null ? null : fnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fn_info.fn_number
     *
     * @return the value of fn_info.fn_number
     *
     * @mbg.generated
     */
    public Integer getFnNumber() {
        return fnNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fn_info.fn_number
     *
     * @param fnNumber the value for fn_info.fn_number
     *
     * @mbg.generated
     */
    public void setFnNumber(Integer fnNumber) {
        this.fnNumber = fnNumber;
    }
}