package com.baohao.departmentwebsitefrontend.model;

import java.util.ArrayList;
import java.util.List;

public class SnInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sn_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sn_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sn_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sn_info
     *
     * @mbg.generated
     */
    public SnInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sn_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sn_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sn_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sn_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sn_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sn_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sn_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sn_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sn_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sn_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sn_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSnIdIsNull() {
            addCriterion("sn_id is null");
            return (Criteria) this;
        }

        public Criteria andSnIdIsNotNull() {
            addCriterion("sn_id is not null");
            return (Criteria) this;
        }

        public Criteria andSnIdEqualTo(Integer value) {
            addCriterion("sn_id =", value, "snId");
            return (Criteria) this;
        }

        public Criteria andSnIdNotEqualTo(Integer value) {
            addCriterion("sn_id <>", value, "snId");
            return (Criteria) this;
        }

        public Criteria andSnIdGreaterThan(Integer value) {
            addCriterion("sn_id >", value, "snId");
            return (Criteria) this;
        }

        public Criteria andSnIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sn_id >=", value, "snId");
            return (Criteria) this;
        }

        public Criteria andSnIdLessThan(Integer value) {
            addCriterion("sn_id <", value, "snId");
            return (Criteria) this;
        }

        public Criteria andSnIdLessThanOrEqualTo(Integer value) {
            addCriterion("sn_id <=", value, "snId");
            return (Criteria) this;
        }

        public Criteria andSnIdIn(List<Integer> values) {
            addCriterion("sn_id in", values, "snId");
            return (Criteria) this;
        }

        public Criteria andSnIdNotIn(List<Integer> values) {
            addCriterion("sn_id not in", values, "snId");
            return (Criteria) this;
        }

        public Criteria andSnIdBetween(Integer value1, Integer value2) {
            addCriterion("sn_id between", value1, value2, "snId");
            return (Criteria) this;
        }

        public Criteria andSnIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sn_id not between", value1, value2, "snId");
            return (Criteria) this;
        }

        public Criteria andSnNameIsNull() {
            addCriterion("sn_name is null");
            return (Criteria) this;
        }

        public Criteria andSnNameIsNotNull() {
            addCriterion("sn_name is not null");
            return (Criteria) this;
        }

        public Criteria andSnNameEqualTo(String value) {
            addCriterion("sn_name =", value, "snName");
            return (Criteria) this;
        }

        public Criteria andSnNameNotEqualTo(String value) {
            addCriterion("sn_name <>", value, "snName");
            return (Criteria) this;
        }

        public Criteria andSnNameGreaterThan(String value) {
            addCriterion("sn_name >", value, "snName");
            return (Criteria) this;
        }

        public Criteria andSnNameGreaterThanOrEqualTo(String value) {
            addCriterion("sn_name >=", value, "snName");
            return (Criteria) this;
        }

        public Criteria andSnNameLessThan(String value) {
            addCriterion("sn_name <", value, "snName");
            return (Criteria) this;
        }

        public Criteria andSnNameLessThanOrEqualTo(String value) {
            addCriterion("sn_name <=", value, "snName");
            return (Criteria) this;
        }

        public Criteria andSnNameLike(String value) {
            addCriterion("sn_name like", value, "snName");
            return (Criteria) this;
        }

        public Criteria andSnNameNotLike(String value) {
            addCriterion("sn_name not like", value, "snName");
            return (Criteria) this;
        }

        public Criteria andSnNameIn(List<String> values) {
            addCriterion("sn_name in", values, "snName");
            return (Criteria) this;
        }

        public Criteria andSnNameNotIn(List<String> values) {
            addCriterion("sn_name not in", values, "snName");
            return (Criteria) this;
        }

        public Criteria andSnNameBetween(String value1, String value2) {
            addCriterion("sn_name between", value1, value2, "snName");
            return (Criteria) this;
        }

        public Criteria andSnNameNotBetween(String value1, String value2) {
            addCriterion("sn_name not between", value1, value2, "snName");
            return (Criteria) this;
        }

        public Criteria andSnNumberIsNull() {
            addCriterion("sn_number is null");
            return (Criteria) this;
        }

        public Criteria andSnNumberIsNotNull() {
            addCriterion("sn_number is not null");
            return (Criteria) this;
        }

        public Criteria andSnNumberEqualTo(Integer value) {
            addCriterion("sn_number =", value, "snNumber");
            return (Criteria) this;
        }

        public Criteria andSnNumberNotEqualTo(Integer value) {
            addCriterion("sn_number <>", value, "snNumber");
            return (Criteria) this;
        }

        public Criteria andSnNumberGreaterThan(Integer value) {
            addCriterion("sn_number >", value, "snNumber");
            return (Criteria) this;
        }

        public Criteria andSnNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("sn_number >=", value, "snNumber");
            return (Criteria) this;
        }

        public Criteria andSnNumberLessThan(Integer value) {
            addCriterion("sn_number <", value, "snNumber");
            return (Criteria) this;
        }

        public Criteria andSnNumberLessThanOrEqualTo(Integer value) {
            addCriterion("sn_number <=", value, "snNumber");
            return (Criteria) this;
        }

        public Criteria andSnNumberIn(List<Integer> values) {
            addCriterion("sn_number in", values, "snNumber");
            return (Criteria) this;
        }

        public Criteria andSnNumberNotIn(List<Integer> values) {
            addCriterion("sn_number not in", values, "snNumber");
            return (Criteria) this;
        }

        public Criteria andSnNumberBetween(Integer value1, Integer value2) {
            addCriterion("sn_number between", value1, value2, "snNumber");
            return (Criteria) this;
        }

        public Criteria andSnNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("sn_number not between", value1, value2, "snNumber");
            return (Criteria) this;
        }

        public Criteria andSnDocIsNull() {
            addCriterion("sn_doc is null");
            return (Criteria) this;
        }

        public Criteria andSnDocIsNotNull() {
            addCriterion("sn_doc is not null");
            return (Criteria) this;
        }

        public Criteria andSnDocEqualTo(String value) {
            addCriterion("sn_doc =", value, "snDoc");
            return (Criteria) this;
        }

        public Criteria andSnDocNotEqualTo(String value) {
            addCriterion("sn_doc <>", value, "snDoc");
            return (Criteria) this;
        }

        public Criteria andSnDocGreaterThan(String value) {
            addCriterion("sn_doc >", value, "snDoc");
            return (Criteria) this;
        }

        public Criteria andSnDocGreaterThanOrEqualTo(String value) {
            addCriterion("sn_doc >=", value, "snDoc");
            return (Criteria) this;
        }

        public Criteria andSnDocLessThan(String value) {
            addCriterion("sn_doc <", value, "snDoc");
            return (Criteria) this;
        }

        public Criteria andSnDocLessThanOrEqualTo(String value) {
            addCriterion("sn_doc <=", value, "snDoc");
            return (Criteria) this;
        }

        public Criteria andSnDocLike(String value) {
            addCriterion("sn_doc like", value, "snDoc");
            return (Criteria) this;
        }

        public Criteria andSnDocNotLike(String value) {
            addCriterion("sn_doc not like", value, "snDoc");
            return (Criteria) this;
        }

        public Criteria andSnDocIn(List<String> values) {
            addCriterion("sn_doc in", values, "snDoc");
            return (Criteria) this;
        }

        public Criteria andSnDocNotIn(List<String> values) {
            addCriterion("sn_doc not in", values, "snDoc");
            return (Criteria) this;
        }

        public Criteria andSnDocBetween(String value1, String value2) {
            addCriterion("sn_doc between", value1, value2, "snDoc");
            return (Criteria) this;
        }

        public Criteria andSnDocNotBetween(String value1, String value2) {
            addCriterion("sn_doc not between", value1, value2, "snDoc");
            return (Criteria) this;
        }

        public Criteria andFnIdIsNull() {
            addCriterion("fn_id is null");
            return (Criteria) this;
        }

        public Criteria andFnIdIsNotNull() {
            addCriterion("fn_id is not null");
            return (Criteria) this;
        }

        public Criteria andFnIdEqualTo(Integer value) {
            addCriterion("fn_id =", value, "fnId");
            return (Criteria) this;
        }

        public Criteria andFnIdNotEqualTo(Integer value) {
            addCriterion("fn_id <>", value, "fnId");
            return (Criteria) this;
        }

        public Criteria andFnIdGreaterThan(Integer value) {
            addCriterion("fn_id >", value, "fnId");
            return (Criteria) this;
        }

        public Criteria andFnIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fn_id >=", value, "fnId");
            return (Criteria) this;
        }

        public Criteria andFnIdLessThan(Integer value) {
            addCriterion("fn_id <", value, "fnId");
            return (Criteria) this;
        }

        public Criteria andFnIdLessThanOrEqualTo(Integer value) {
            addCriterion("fn_id <=", value, "fnId");
            return (Criteria) this;
        }

        public Criteria andFnIdIn(List<Integer> values) {
            addCriterion("fn_id in", values, "fnId");
            return (Criteria) this;
        }

        public Criteria andFnIdNotIn(List<Integer> values) {
            addCriterion("fn_id not in", values, "fnId");
            return (Criteria) this;
        }

        public Criteria andFnIdBetween(Integer value1, Integer value2) {
            addCriterion("fn_id between", value1, value2, "fnId");
            return (Criteria) this;
        }

        public Criteria andFnIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fn_id not between", value1, value2, "fnId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sn_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sn_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}