package com.baohao.departmentwebsitefrontend.dao;

import com.baohao.departmentwebsitefrontend.model.ImageGroupInfo;
import com.baohao.departmentwebsitefrontend.model.ImageGroupInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImageGroupInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_group_info
     *
     * @mbg.generated
     */
    long countByExample(ImageGroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_group_info
     *
     * @mbg.generated
     */
    int deleteByExample(ImageGroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_group_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_group_info
     *
     * @mbg.generated
     */
    int insert(ImageGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_group_info
     *
     * @mbg.generated
     */
    int insertSelective(ImageGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_group_info
     *
     * @mbg.generated
     */
    List<ImageGroupInfo> selectByExample(ImageGroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_group_info
     *
     * @mbg.generated
     */
    ImageGroupInfo selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_group_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ImageGroupInfo record, @Param("example") ImageGroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_group_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ImageGroupInfo record, @Param("example") ImageGroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_group_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ImageGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_group_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ImageGroupInfo record);
}